FROM ubuntu:22.04

RUN apt-get update && \
    apt-get install -y build-essential openmpi-bin libopenmpi-dev python3 python3-pip && \
    pip3 install --no-cache-dir --upgrade pip

ENV OMPI_ALLOW_RUN_AS_ROOT=1
ENV OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1

COPY jogodavida_openmp_mpi.c /app/
COPY openmp_server.py /app/

WORKDIR /app

RUN mpicc jogodavida_openmp_mpi.c -o jogodavida_mpi

CMD ["python3", "openmp_server.py"]
